language: go

services:
  docker

go:
  - "1.13"

script:
  - if [ -n "$(gofmt -l ./plugin)" ]; then echo "Go code is not formatted:"; gofmt -d ./plugin; exit 1; fi
  - make up && sleep 30
  - make test-client

deploy:
  skip_cleanup: true
  - provider: script
    script:
      - echo "hello" && echo "goodbye"
    on:
      branch: master


cache:
  directories:
    - $GOPATH/pkg
    - /tmp/gopath-pkg
